name: demo workflow    # name of the workflow
on:                    # on: key defines the trigger (trigger on push to branches)
  push:
    branches:
      - main
      - "feature/**"   # any feature branch (pattern matching for branch names)
 
jobs:
  demo-job:
    name: demo job
    runs-on: ubuntu-latest
    steps:
      - name: message 1
        run: echo "This is message 1"    #(shell command)
      - name: message 2
        run: echo "This is message 2"    #(shell command)
